project_id = "jlicpikvuohwgfqtdltn"

[functions.paypal-create-subscription]
verify_jwt = false

[functions.paypal-activate-subscription]
verify_jwt = false

[functions.paypal-cancel-subscription]
verify_jwt = false